# Source folder for each module
domain-src: domain/src/main/java # Domain java sources
db-adapter-src: driven/database/src/main/java # DB adapter java sources
rest-adapter-src: driving/rest-api/src/main/java # Rest adapter java sources

domain-models-pkg: {{cookiecutter.package}}.domain.models # domain models package
domain-commands-pkg: {{cookiecutter.package}}.domain.models.commands # domain commands package
domain-in-ports-pkg: {{cookiecutter.package}}.domain.ports.driving # domain ports (in/driving/application)
domain-out-ports-pkg: {{cookiecutter.package}}.domain.ports.driven # domain ports (out/driven/infrastructure)
domain-use-cases-pkg: {{cookiecutter.package}}.domain.services
domain-exceptions-pkg: {{cookiecutter.package}}.domain.exceptions

db-adapters-pkg: {{cookiecutter.package}}.database.adapters # db adapters (port implementations)
db-models-pkg: {{cookiecutter.package}}.database.models # db entities package
db-repositories-pkg: {{cookiecutter.package}}.database.repositories # db repositories package
db-mapper-pkg: {{cookiecutter.package}}.database.mapper # db mapper package

rest-models-pkg: {{cookiecutter.package}}.restapi.models # rest models package
rest-controllers-pkg: {{cookiecutter.package}}.restapi.controllers # rest controllers package
rest-exception-handler-pkg: {{cookiecutter.package}}.restapi.config # rest exception handler package
rest-mapper-pkg: {{cookiecutter.package}}.restapi.mappers # rest mappers package
